server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:6606}/${MYSQL_DB_NAME:playground}?serverTimezone=Asia/Singapore"
    password: ${DATABASE_PASSWORD:pass}
    username: ${DATABASE_USER:user}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    check-location: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:ci}
  output.ansi.enabled: always
logging:
  level:
    root: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%logger{0}:%L){cyan} - %msg%n"
